stages:
    - build
    - deploy

build_application:
    stage: build
    tags:
        - front-docker
    artifacts:
        paths:
        - dist
        - pnpm-lock.yaml
        expire_in: 2 days

    only:
        - master
    script:
        - pnpm
        - pnpm build

dev_stage:
    stage: deploy
    tags:
        - front-docker
    only:
        - master
    image: kroniak/ssh-client
    before_script:
        - mkdir -p ~/.ssh
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - echo -n "$SSH_KEY" | base64 -d > ~/.ssh/id_rsa
        - chmod 700 ~/.ssh
        - chmod 600 ~/.ssh/id_rsa

    script:
        - ls -la ~/.ssh/
        - ssh -v root@$DEV_HOST
        - cd dist
        - ssh root@$DEV_HOST 'rm -r /union/dev-union-web-client; mkdir /union/1532-union-web-client;'
        - scp -r index.html root@$DEV_HOST:/union/1532-union-web-client
        - scp -r favicon.ico root@$DEV_HOST:/union/1532-union-web-client
        - scp -r js root@$DEV_HOST:/union/1532-union-web-client
        - scp -r img root@$DEV_HOST:/union/1532-union-web-client
        - scp -r css root@$DEV_HOST:/union/1532-union-web-client
        - scp -r fonts root@$DEV_HOST:/union/1532-union-web-client

